USE [master]
GO

/****** Object:  Database [autoservice]    Script Date: 10.04.2022 20:18:33 ******/
CREATE DATABASE [autoservice]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'autoservice', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\autoservice.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'autoservice_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\autoservice_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [autoservice].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [autoservice] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [autoservice] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [autoservice] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [autoservice] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [autoservice] SET ARITHABORT OFF 
GO

ALTER DATABASE [autoservice] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [autoservice] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [autoservice] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [autoservice] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [autoservice] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [autoservice] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [autoservice] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [autoservice] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [autoservice] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [autoservice] SET  DISABLE_BROKER 
GO

ALTER DATABASE [autoservice] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [autoservice] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [autoservice] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [autoservice] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [autoservice] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [autoservice] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [autoservice] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [autoservice] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [autoservice] SET  MULTI_USER 
GO

ALTER DATABASE [autoservice] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [autoservice] SET DB_CHAINING OFF 
GO

ALTER DATABASE [autoservice] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [autoservice] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [autoservice] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [autoservice] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [autoservice] SET QUERY_STORE = OFF
GO

ALTER DATABASE [autoservice] SET  READ_WRITE 
GO

