//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuckShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpeningHour
    {
        public int Id { get; set; }
        public int PointOfSale { get; set; }
        public string Day { get; set; }
        public System.TimeSpan StartWork { get; set; }
        public System.TimeSpan EndWork { get; set; }
        public System.TimeSpan StartDinner { get; set; }
        public System.TimeSpan ExitDinner { get; set; }
    
        public virtual PointOfSale PointOfSale1 { get; set; }
    }
}
