//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuckShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrafficPaht
    {
        public int Id { get; set; }
        public int PointOfSale { get; set; }
        public System.DateTime Datetime { get; set; }
        public string Direction { get; set; }
    
        public virtual PointOfSale PointOfSale1 { get; set; }
    }
}
